name: Deploy to Aliyun ECS
on:
  push:
    branches:
      - main # 可按需修改为实际分支，如master等，指定在哪些分支有push事件时触发工作流
jobs:
  build-and-deploy:
    runs-on: ubuntu -latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 拉取仓库代码
      - name: Set up Node.js (如果项目是Node.js项目，按需修改)
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 按需指定Node.js版本
      - name: Install dependencies (如果项目有依赖，按需操作)
        run: npm install # 如果是Node.js项目，安装依赖，其他项目需替换为对应命令
      - name: Build project (如果项目需要构建，按需操作)
        run: npm run build # 如果是Node.js项目构建命令，其他项目需替换为对应构建命令
      - name: Deploy to ECS
        uses: appleboy/ssh-action@v0.1.0 # 使用ssh-action将文件传输并部署到服务器
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }} # 如果使用密钥对登录
          # password: ${{ secrets.SSH_PASSWORD }} # 如果使用密码登录，需取消注释此行
          script: |
            cd /var/www/html
            rm -rf *
            mkdir -p assets
            scp -r ${{ github.workspace }}/* .
            systemctl restart nginx
