name: Deploy H5 to Aliyun

on:
  push:
    branches:
      - main
      - aliyun
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress
        run: pnpm docs:build

      - name: Configure Aliyun OSS
        uses: alibaba/oss-util-action@v1
        with:
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          region: cn-heyuan
          bucket: your-bucket-name
          folder: docs/.vitepress/dist
